name: Publish image
on:
  push:
    branches:
      - main
    paths:
      - Dockerfile

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - uses: actions/checkout@v4
  
      - name: Build image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: framadatectl
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Dockerfile

      - name: Push image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
